reactjs/ru.react.dev

TRANSLATION.md
=> RFC: key, ref, reconciliation, bundler

TRANSLATION.md
https://github.com/reactjs/ru.reactjs.org/issues/4#issuecomment-461977978
=> RFC: Split render definition

TRANSLATION.md
По аналогии с флекс-контейнер из вебстандартов, но с DOM.
=> RFC: DOM-контейнер

TRANSLATION.md
Готов выслушать идеи касательно "warning", мне просто нужно было что-то использовать в одном из переводов уже.
Tip и Warning часто используются как заголовки во вставках.
=> Propose "Tip" and "Warning" translations (used in inserts).

TRANSLATION.md
=> Терминология: жизненный цикл

TRANSLATION.md
=> Терминология: разработка, режим разработки

TRANSLATION.md
=> tutorial -> введение, на основе #41

TRANSLATION.md
=> Терминология: возможность

content/warnings/legacy-factories.md
Перенёс перевод без изменений из Crowdin - https://crowdin.com/translate/react/1042/en-ru
+ требуется рассмотреть согласование перевода `In Depth` и занести в словарь.
=> Translate React Element Factories and JSX Warning

TRANSLATION.md
Мне не очень нра, но лучше вариантов не знаю?
Может в конкретных случаях будет лучше изолированный или обособленный, но не уверен.
=> Терминология: инкапсуляция, инкапсулированный

TRANSLATION.md
У нас уже есть какая-то договорённость про stateful/stateless components? Мне не нравится, что в три слова, но я не вижу альтернатив.
=> Терминология: компонент с состоянием/без состояния

TRANSLATION.md
=> Терминология: однонаправленный поток данных

TRANSLATION.md
=> Терминология: редюсер, контекст

TRANSLATION.md
https://github.com/reactjs/ru.reactjs.org/issues/63
=> Терминология: побочный эффект

TRANSLATION.md
=> Терминология: пользовательские хуки

TRANSLATION.md
=> Терминология: helper

TRANSLATION.md
https://github.com/reactjs/ru.reactjs.org/issues/92#issuecomment-462492107
=> Терминология: fallback

TRANSLATION.md
¯\\_(ツ)_/¯
Другие варианты:
* запасные пути
* запасные выходы
=> Терминология: лазейки

TRANSLATION.md
После обсуждения https://github.com/reactjs/ru.reactjs.org/issues/114
=> Терминология: cross cutting concerns

TRANSLATION.md
https://github.com/reactjs/ru.reactjs.org/issues/107#issuecomment-462956794
=> Терминология: bind

TRANSLATION.md
=> Терминология: folder

TRANSLATION.md
https://github.com/reactjs/ru.reactjs.org/issues/127#issuecomment-463379466
=> Терминология: snapshot

TRANSLATION.md
https://github.com/reactjs/ru.reactjs.org/issues/105#issuecomment-462940075
=> Терминология: native

TRANSLATION.md
https://github.com/reactjs/ru.reactjs.org/issues/105#issuecomment-462936954
=> Терминология: ref forwarding

TRANSLATION.md
=> Терминология: destructuring

TRANSLATION.md
=> Терминология: persistent

TRANSLATION.md
=> Терминология: TLDR

TRANSLATION.md
=> Терминология: хук

TRANSLATION.md
https://github.com/reactjs/ru.reactjs.org/pull/143#discussion_r257260819
=> Терминология: codemod

TRANSLATION.md
=> Убрал остатки испанского из очень плохого примера

TRANSLATION.md
https://github.com/reactjs/ru.reactjs.org/pull/98#discussion_r
=> Терминология: feature/функционал

content/warnings/dont-call-proptypes.md
Фикс для https://github.com/reactjs/ru.reactjs.org/pull/143#issuecomment-466105110
https://app.netlify.com/sites/ru-reactjs/deploys/5c6ee83c16a791000831f0b9
=> wrap dont-call-propTypes into doublequotes

content/docs/hooks-state.md
=> Fix missed translation in hooks-state

content/docs/faq-functions.md
=> Fix typos, missed translation in faq-functions

src/templates/components/NavigationFooter/NavigationFooter.js
Или не _статья_, а _раздел_ или _страница_?
=> Перевод навигации по страницам

gatsby-config.js, package.json, plugins/gatsby-remark-typography/gatsby-node.js, plugins/gatsby-remark-typography/package.json, yarn.lock
=> Интеграция типографа

content/docs/addons-test-utils.md
=> Fix typos in addons-test-utils

content/home/examples/a-component-using-external-plugins.js
<details><summary>было</summary><p>
</p></details>
<details><summary>стало</summary><p>
</p></details>
=> Текст на главной странице в примере с markdown редактором

content/docs/hooks-intro.md
=> Translated text in code

content/docs/hooks-faq.md
Правка в соответствии с соглашением по переводу (глоссарий TRANSLATION.md)
=> fix typo error

content/docs/create-a-new-react-app.md
=> Very little fix

content/docs/testing-recipes.md
Исправление ошибки: убедится -> убедиться
=> Fix typo in testing-recipes

content/docs/higher-order-components.md
The same link already updated in original repo.
=> Outdated link in higher-order-components.md

TRANSLATION.md
Обсуждение в https://github.com/reactjs/ru.reactjs.org/issues/423
=> Add concurrent mode translation

content/blog/2013-06-02-jsfiddle-integration.md
=> Add `JSFiddle Integration` translation

content/tutorial/tutorial.md
Удаление части англоязычного текста, видимо, оставшегося после перевода.
=> Removed part of already translated english text

content/docs/hooks-faq.md
Исправлен баг: Неправильное отображение заголовка в `https://ru.reactjs.org/docs/hooks-faq.html`
=> Баг отображения заголовок

src/content/learn/react-developer-tools.md
Translation for "React Developer Tools"
=> Translation for "React Developer Tools" 

src/content/learn/index.md
=> Updated page title
