- TRANSLATION.md
На английском мы отошли от "functional" в сторону "function component". То есть компонент-класс и компонент-функция. Но это как-то совсем странно по-русски.
Думаю ок будет оставить функциональный/классовый компонент. Кажется относительно популярно так уже.
В будущем это будет не так релевантно по мере того как классы уходят на второй план.
> Терминология: функциональный/классовый компонент

- TRANSLATION.md
Можно конечно «локальное», но мне кажется русское слово «внутреннее» имеет тот же смысл, и даже в контексте реакта встречается чаще.
> Терминология: внутреннее состояние

- TRANSLATION.md
> Терминология: группировка, обновление, группа обновлений

- TRANSLATION.md
Error boundaries слишком новые, я особо в русском вариантов не видел. Мне кажется, предохранитель очень четкая метафора, и это лучше «границ ошибки».
Suspense пока на русском вообще нет (слишком новая фича), мне кажется есть шанс назвать это «задержкой».
> Терминология: задержка, предохранитель

- TRANSLATION.md
Хочу убрать гендер, так что «разработки», а не «разработчика».
> Терминология: инструменты разработки

- content/docs/conditional-rendering.md
Это изменение уже прошло ревью в #60, но я по неосторожности упустил коммит перед мёржем.
> Пропущенное исправление в conditional-rendering

- content/docs/nav.yml
- content/docs/reference-javascript-environment-requirements.md
> JS environment-requirements

- content/warnings/refs-must-have-owner.md
Добавил кавычки в `title` в файле `content/warnings/refs-must-have-owner.md`.
Иначе gatsby при сборке писал ошибку
```
error Error processing Markdown file /home/tesler/git/ru.reactjs.org/content/warnings/refs-must-have-owner.md:
incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 2, column 22:
title: Предупреждение: У рефа должен быть владелец
^
```
и страница не отображалась.
> Fix title in refs-must-have-owner.md

- content/docs/reference-events.md
Для "Media Events" использовал перевод из [MDN](https://developer.mozilla.org/ru/docs/Web/Guide/Events/Media_events).
> Fix reference-events.md

- content/docs/typechecking-with-proptypes.md
> Fix typo in typechecking-with-proptypes

- content/docs/reference-events.md
> Fix missed typos in reference-events

- content/docs/lists-and-keys.md
> Fix typo in lists-and-keys

- content/docs/render-props.md
> Fix typos, missed translations in render-props

- src/components/LayoutHeader/Header.js
Несмотря на то, что просится перевод "Языки", я хочу предложить вариант "Переводы". Не знаю как в англ, но русском это лучше понимается...
Например, так сделано в [русском переводе Vue.js](https://ru.vuejs.org/v2/guide/index.html), но там и в оригинале не _Languages_, а _Translations_. Но, возможно, есть какая-то тонкая разница между этим, поэтому открываю PR.
> Header: translate link to Languages page

- content/404.md
- src/pages/404.js
По запросу из https://github.com/reactjs/ru.reactjs.org/issues/224
> Translation of 404 page

- gatsby-config.js
- plugins/gatsby-remark-typography/gatsby-node.js
- plugins/gatsby-remark-typography/index.js
Короче немного ошибся с тем, как должен работать типограф :man_facepalming: 
В общем, файл `gatsby-node.js` - типографирует заголовки, `index.js` - текстовые узлы Markdown-дерева (с отключением удалением пробелов справа и слева, нужно чтобы корректно отображался конечный HTML).
Всё, теперь работает, как и должен.
> Корректная работа типографа

- src/components/LayoutHeader/Header.js
Current:
With PR:
En original:
> Fixing header, search bar no more overlaps link

- plugins/gatsby-remark-typography/index.js
Плагин `gatsby-remark-typography` трансформирует `W3C` в `W3 °C`.
Из-за правила [common/symbols/cf](https://github.com/typograf/typograf/blob/dev/src/rules/common/symbols/cf.js) для [Типографа](https://github.com/typograf/typograf)
Например страница [Обработка событий](https://ru.reactjs.org/docs/handling-events.html) (Ссылка `спецификацией W3 °C`)
[Исправленная страница](https://deploy-preview-299--ru-reactjs.netlify.com/docs/handling-events.html)
> Fix displaying W3C

- content/community/conferences.md
- content/docs/reference-react-dom.md
Обновлён `conferences.md`. Удален дубликат конференции "React Rally".
Обновлён `reference-react-dom.md`. Добавил пропущенный якорь.
> Update conferencesand reference-react-dom

- content/docs/hooks-faq.md
`height` is not defined in this example, should be `rect.height`
`rect` is DOMRect element so we can grab `width` or `height` from it.
> fix(DOM section): height -> rect.height

- content/docs/optimizing-performance.md
Text tells "there are more two libraries..." but describes three libraries
> Wrong counter of libraries

- content/docs/hooks-reference.md
Исправлен блок совета: убрана лишняя пустая строка, которая разбивала его на две части.
> Fix blockquote

- content/docs/hooks-reference.md
On the English version in this place used "MyContext.Consumer" instead of "MyContext.Provider"
> fix typo on hooks api reference page

- content/docs/reference-test-renderer.md
> translate TestRenderer.act()

- content/blog/2018-11-13-react-conf-recap.md
> Translate "React Conf recap: Hooks, Suspense, and Concurrent Rendering" blog post

- content/docs/state-and-lifecycle.md
> Компонент может передать своё состояние вниз по дереву в виде пропсов дочерних компонентов:
>
>`<h2>Сейчас {this.state.date.toLocaleTimeString()}.</h2>`
Некорректный пример кода. `<h2>...</h2>` является не компонентом, а элементом, у него нет пропсов и в них ничего не передаётся.
В оригинале этого куска кода нет, предлагаю и в переводе тоже опустить его.
> fixed translation

- content/blog/2013-07-26-react-v0-4-1.md
Reverts reactjs/ru.reactjs.org#556
> Revert "Update 2013-07-26-react-v0-4-1.md"

- content/docs/accessibility.md
> Add translation to russian

- content/docs/reference-react-component.md
Исправлена небольшая опечатка на странице [React.Component#ComponentDidCatch](https://ru.reactjs.org/docs/react-component.html#componentdidcatch).
> Fixed a typo in ComponentDidCatch reference section

- content/docs/static-type-checking.md
I have changed the link in the Typescript.
> I have changed the link in the Typescript.

- content/docs/typechecking-with-proptypes.md
Привет,
Я заметил в документации некоторые несоответствия перевода для [PropTypes](https://reactjs.org/docs/typechecking-with-proptypes.html), которые были устранены данным PR.
**Текущий вариант перевода**: "_Ограничение на один дочерний компонент
С помощью `PropTypes.element` вы можете указать, что в качестве дочернего может быть передан только один элемент._", изменен в соответствии с оригинальным текстом ( см. screenshot ).
**Обновленный перевод**: "_Требование одного дочернего элемента
С помощью `PropTypes.element` вы можете указать, что только один дочерний элемент может быть передан компоненту в качестве потомка._"
> Improve translation for PropTypes (requiring-single-child)

- content/docs/static-type-checking.md
> Current link to Typescript React Starter lead to "404 Not Found".  She has been replaced with the correct one

- content/docs/strict-mode.md
Добавление перевода для обновлённой части страницы о Strict Mode.
Ссылка на EN версию: [Link](https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state).
> Update translation for Strict mode

- content/docs/reference-react.md
> Adds a translation into Russian

- content/docs/hooks-reference.md
- content/docs/reference-react-dom.md
Добрый день,
- изменила версию в ссылках на cdn с 17 на 18ю
- привела страницу ReactDOM в аналогичное состояние с [EN-версией](https://reactjs.org/docs/react-dom.html)
- добавила информацию на страницу справочника хуков про обновления в 18й версии
> Update info about hooks and react-dom

- src/content/reference/react/startTransition.md
> Translate startTransition

- src/content/reference/react-dom/index.md
Translation for "React DOM APIs"
> Translation for "React DOM APIs" 

- src/content/learn/render-and-commit.md
Привееет 👋
Нашёл в тексте одну опечатку, и возможно, ещё одну пунктуационную ошибку, закинул PR :)
#
> FIX: typography of render-and-commit article
